start choco install -y 7zip
start choco install -y flashplayerplugin
start choco install -y flashplayeractivex
start choco install -y flashplayerppapi
start choco install -y vlc
start choco install -y recuva
start choco install -y anki
start choco install -y jre8
start choco install -y firefox
start choco install -y googlechrome
start choco install -y javaruntime
start choco install -y git
start choco install -y putty
start choco install -y jdk8
start choco install -y filezilla
start choco install -y procexp
start choco install -y foxitreader
start choco install -y treesizefree
start choco install -y chocolateygui
start choco install -y teamviewer
start choco install -y audacity
start choco install -y cpu-z
start choco install -y eclipse
start choco install -y autoit.install
start choco install -y virtualclonedrive
start choco install -y origin
start choco install -y avidemux
start choco install -y coretemp
start choco install -y epicgameslauncher
start choco install -y visualstudiocode
start choco install -y zerotier-one
start choco install -y openvpn
start choco install -y teamspeak
start choco install -y vcredist-all
start choco install -y visualcpp-build-tools
start choco install -y microsoft-visual-cpp-build-tools
